config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'ask', to: 'questions#ask'
  get 'answer', to: 'questions#answer'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def ask; end

  def answer
    @message = params[:answer]
    answers = ['Great!', 'Silly question, get dressed and go to work!', "I don't care, get dressed and go to work!"]
    @answer = if @message == 'I am going to work'
                answers[0]
              elsif @message.include? '?'
                answers[1]
              else
                answers[2]
              end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<h1>Stupid Coaching</h1>

<div class="user">
  <p><%= @message %></p>
  <p>-You</p>
</div>

<div class="coach">
<p><%= @answer %></p>
<p>-Your coach</p>
</div>

<%= link_to 'Ask a new question', ask_path %>

app/views/questions/ask.html.erb
<h1>Stupid Coaching</h1>

<form action="/answer" method="get">
  <input type="text" name="answer">
  <input type="submit" value="Ask!">
</form>